language: python
cache:
  - pip: true
python:
  - "3.5"
before_install:
  - |
    mkdir -p $HOME/.config/matplotlib && \
    echo 'backend: agg' > $HOME/.config/matplotlib/matplotlibrc
install:
  - python setup.py install
  - pip install pytest
script: pytest
