language: python
cache:
  - pip: true
python:
  - "3.6"
before_install:
  - |
    mkdir -p $HOME/.config/matplotlib && \
    echo 'backend: agg' > $HOME/.config/matplotlib/matplotlibrc
install:
  - pip install .
  - pip install pytest
script: pytest tests
