CURVE_MINIMUM_DURATION_HOURS = 5

PHASE_MINIMUM_SIGNAL_NOISE_RATIO = 1.0
PHASE_MINIMUM_DURATION_HOURS = 1.5
PHASE_MINIMUM_SLOPE = 0.005

PHASE_RANK_EXCLUDE_BELOW = 33
PHASE_RANK_WEIGHTS = {
    "SNR": 50,
    "duration": 30,
    "slope": 10,
    # TODO add 1 - start?
}
